### ISSUE TITLE
請問一下 設置

### ISSUE THREAD

**Issue by makstfate** [cythilya/nightwatch101#1]
想請問一下 當我執行 npm test後
他顯示nightwatch --env local
Starting selenium server in parallel mode...
然後就沒有任何動作了

不知道是哪裡出了問題
看一些教學只大約說了
chromedriver.exe 2.15
selenium-server-standalone-3.8.1.jar
但是不知到實際要放的位置在哪
跟有甚麼原因為造成 停在
Starting selenium server in parallel mode...
的狀態下

**Comment by cythilya** [comment]
Hello @makstfate 
請問 java 的版本是？
