### ISSUE TITLE
Nightwatch101 #7：指令 Part 1 和 Nightwatch101 #8：指令 Part 2  請問cookie 是沿用嗎？

### ISSUE THREAD

**Issue by puff-tw** [cythilya/nightwatch101#2]
因為登入的cookie 和 未登入的 cookie 是有不同的用途。
但是我不曉得你的兩個測試案例是有連慣性嗎？還是各別分開？
我的意思是，你是拿 part 1 登入後的 cookie 拿去做後面 part 2 的動作嗎？( 看起來不像 )
part 2 比較像是沒登入直接到露天取一個未登入的cookie ，我這樣說對嗎？

[Nightwatch101 #7：指令 Part 1](https://ithelp.ithome.com.tw/articles/10191927)
[Nightwatch101 #8：指令 Part 2](https://ithelp.ithome.com.tw/articles/10192027)

如果兩個案例是分開的，
我覺得測試案例，可以加一個 未登入的 cookie，來去拜託要登入才能用的頁面。

希望後面的案例能有更多實務上面的例子或情境。

最後感謝@cythilya 的用心教學。 :clap:  :tada:

**Comment by cythilya** [comment]
這裡的範例基本上是沒有連貫性的，很抱歉沒有注意到這部份，讓登入/未登入狀態交錯著，造成跑範例時候的困擾，之後會改進。

感謝建議，我會加油 :)

**Comment by puff-tw** [comment]
雖然開正式環境的網站來跑測試是ok的，
但有些情況是不被允許，比如重要功能，刪帳號之類的，測完一次就不能測了。
而且最好測試是可以一直被 repoduce 。
更多時候我們都是在本機上面跑，跑之前會先檢查資料完整性 或是 類似跑 db seed 讓它把假資料補完，再測試。

可以考慮把以下 todo 參考放在 README.md 上面

## TODO
- [ ]  localhost test
- [ ]  是否能設定假的https certificate，然後bypass https
- [ ] 假資料填充
- [ ] 假資料測完後移除

**Comment by cythilya** [comment]
受教了，感謝寶貴的意見！
